name = "bimgle"
author = "AIGO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cc470c26e45a2b8b78b2e8de5f041805c3d76855047692076a7787762264969"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
