name = "bimgle"
author = "AIGO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fd81a63d59981da553993e924b8472bbb06f0b946b665cd7bb0bca42c078a85"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
