name = "bimgle"
author = "AIGO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86be73f821075053c00536aae1c99ad1ebfef80e33d65048ae96932f967541f3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
