name = "bimgle"
author = "AIGO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63003a2c3f5534c421ba5ac687d98233f6ae7661d5eef798c0e9b39186109ae0"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
