name = "bimgle"
author = "AIGO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "898fb8e6621c2baa887f31c3a6f1584b218872b20f221513b37eda4a0a9e07d7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
