ServerEvents.recipes(event => {
  event.remove({ output: 'terramity:basic_pistol' })
  event.remove({ output: 'terramity:advanced_pistol' })
  event.remove({ output: 'terramity:suppressed_advanced_pistol' })
  event.remove({ output: 'terramity:plague_pistol' })
  event.remove({ output: 'terramity:requiem' })
  event.remove({ output: 'terramity:vulcan' })
  event.remove({ output: 'terramity:big_iron' })
  event.remove({ output: 'terramity:six_shooter' })
  event.remove({ output: 'terramity:celestial_sixty' })
  event.remove({ output: 'terramity:five_thousand_magnum' })
  event.remove({ output: 'terramity:basic_rifle' })
  event.remove({ output: 'terramity:advanced_burst_rifle' })
  event.remove({ output: 'terramity:advanced_automatic_rifle' })
  event.remove({ output: 'terramity:gaias_tempest' })
  event.remove({ output: 'terramity:nihility' })
  event.remove({ output: 'terramity:titanomachy' })
  event.remove({ output: 'terramity:stairway_to_heaven' })
  event.remove({ output: 'terramity:elite_rifle' })
  event.remove({ output: 'terramity:anti_material_rifle' })
  event.remove({ output: 'terramity:antimatter_rifle' })
  event.remove({ output: 'terramity:divine_intervention' })
  event.remove({ output: 'terramity:fortunes_favor' })
  event.remove({ output: 'terramity:sawed_off_shotgun' })
  event.remove({ output: 'terramity:pump_action_shotgun' })
  event.remove({ output: 'terramity:plaguebringer' })
  event.remove({ output: 'terramity:hellfire_flurry' })
  event.remove({ output: 'terramity:asphodel' })
  event.remove({ output: 'terramity:flare_gun' })
  event.remove({ output: 'terramity:meteor_cannon' })
  event.remove({ output: 'terramity:rocket_launcher' })
  event.remove({ output: 'terramity:overclocked_microwave' })
  event.remove({ output: 'terramity:railgun' })
  event.remove({ output: 'terramity:aconductile_laser_rifle' })
  event.remove({ output: 'terramity:slot_machine' })
  event.remove({ output: 'terramity:olympus' })
  console.log('Hello! The recipe event has fired!')
})