PlayerEvents.loggedIn(e=>{
    if (!e.player.stages.has('starting_items')) {
        e.player.stages.add('starting_items')
        e.server.scheduleInTicks(50, callback => {
            e.player.give(Item.of('akashictome:tome', '{"akashictome:data":{ars_nouveau:{Count:1b,id:"ars_nouveau:worn_notebook"},bloodmagic:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"bloodmagic:guide"}},botania:{Count:1b,id:"botania:lexicon"},dynamictrees:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"dynamictrees:guide"}},enchanted:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"enchanted:brewing"}},enchanted_0:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_0","patchouli:book":"enchanted:extraction"}},enchanted_1:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_1","patchouli:book":"enchanted:circle_magic"}},enchanted_2:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_2","patchouli:book":"enchanted:herbology"}},enchanted_3:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_3","patchouli:book":"enchanted:getting_started"}},enchanted_4:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_4","patchouli:book":"enchanted:poppetry"}},hexcasting:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"hexcasting:thehexbook"}},irons_spellbooks:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"irons_spellbooks:iss_guide_book"}},tconstruct:{Count:1b,id:"tconstruct:materials_and_you"},tconstruct_0:{Count:1b,id:"tconstruct:puny_smelting",tag:{"akashictome:definedMod":"tconstruct_0"}},tconstruct_1:{Count:1b,id:"tconstruct:mighty_smelting",tag:{"akashictome:definedMod":"tconstruct_1"}},tconstruct_2:{Count:1b,id:"tconstruct:tinkers_gadgetry",tag:{"akashictome:definedMod":"tconstruct_2"}},tconstruct_3:{Count:1b,id:"tconstruct:fantastic_foundry",tag:{"akashictome:definedMod":"tconstruct_3"}},tconstruct_4:{Count:1b,id:"tconstruct:encyclopedia",tag:{"akashictome:definedMod":"tconstruct_4"}}}}'))
        });
    }
})

ServerEvents.customCommand('the_book', e=>{
    e.player.give(Item.of('akashictome:tome', '{"akashictome:data":{ars_nouveau:{Count:1b,id:"ars_nouveau:worn_notebook"},bloodmagic:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"bloodmagic:guide"}},botania:{Count:1b,id:"botania:lexicon"},dynamictrees:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"dynamictrees:guide"}},enchanted:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"enchanted:brewing"}},enchanted_0:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_0","patchouli:book":"enchanted:extraction"}},enchanted_1:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_1","patchouli:book":"enchanted:circle_magic"}},enchanted_2:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_2","patchouli:book":"enchanted:herbology"}},enchanted_3:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_3","patchouli:book":"enchanted:getting_started"}},enchanted_4:{Count:1b,id:"patchouli:guide_book",tag:{"akashictome:definedMod":"enchanted_4","patchouli:book":"enchanted:poppetry"}},hexcasting:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"hexcasting:thehexbook"}},irons_spellbooks:{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"irons_spellbooks:iss_guide_book"}},tconstruct:{Count:1b,id:"tconstruct:materials_and_you"},tconstruct_0:{Count:1b,id:"tconstruct:puny_smelting",tag:{"akashictome:definedMod":"tconstruct_0"}},tconstruct_1:{Count:1b,id:"tconstruct:mighty_smelting",tag:{"akashictome:definedMod":"tconstruct_1"}},tconstruct_2:{Count:1b,id:"tconstruct:tinkers_gadgetry",tag:{"akashictome:definedMod":"tconstruct_2"}},tconstruct_3:{Count:1b,id:"tconstruct:fantastic_foundry",tag:{"akashictome:definedMod":"tconstruct_3"}},tconstruct_4:{Count:1b,id:"tconstruct:encyclopedia",tag:{"akashictome:definedMod":"tconstruct_4"}}}}'))
})
